Transfer/ViewModels/AccountLogViewModel.cs
using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Transfer.ViewModels
{
    /// <summary>
    /// AccountLogViewModel
    /// </summary>
    public class AccountLogViewModel
    {
        [Description("使用者帳號")]
        public string User_Account { get; set; }

        [Description("使用者名稱")]
        public string User_Name { get; set; }

        [Description("登入時間")]
        public string Login_Time { get; set; }

        [Description("登出時間")]
        public string Logout_Time { get; set; }

        [Description("進入Menu時間")]
        public string Browse_Time { get; set; }

        [Description("Menu參數")]
        public string Menu_Id { get; set; }

        [Description("Menu名稱")]
        public string Menu_Detail { get; set; }

        [Description("Action名稱")]
        public string Action_Name { get; set; }

        [Description("執行動作")]
        public string Event_Name { get; set; }

        [Description("執行開始時間")]
        public string Event_Begin { get; set; }

        [Description("執行結束時間")]
        public string Event_Complete { get; set; }

        [Description("執行結果")]
        public string Event_Flag { get; set; }

        [Description("IP位置")]
        public string IP_Location { get; set; }
    }
}

Transfer/ViewModels/MenuMainViewModel.cs
using System.ComponentModel;

namespace Transfer.ViewModels
{
    public class MenuMainViewModel
    {
        [Description("選單類別")]
        public string Menu { get; set; }

        [Description("選單類別ID")]
        public string Menu_Id { get; set; }

        [Description("選單類別名稱")]
        public string Menu_Detail { get; set; }

        [Description("選單類別圖示")]
        public string Class { get; set; }

        [Description("新增者帳號")]
        public string Create_User { get; set; }

        [Description("新增日期")]
        public string Create_Date { get; set; }

        [Description("新增時間")]
        public string Create_Time { get; set; }

        [Description("最後修改者帳號")]
        public string LastUpdate_User { get; set; }

        [Description("最後修改日期")]
        public string LastUpdate_Date { get; set; }

        [Description("最後修改時間")]
        public string LastUpdate_Time { get; set; }
    }
}

Transfer/ViewModels/MenuSubViewModel.cs
using System.ComponentModel;

namespace Transfer.ViewModels
{
    public class MenuSubViewModel
    {
        [Description("選單類別")]
        public string Menu { get; set; }

        [Description("選單明細ID")]
        public string Menu_Id { get; set; }

        [Description("選單名稱")]
        public string Menu_Detail { get; set; }

        [Description("選單圖示")]
        public string Class { get; set; }

        [Description("View網址")]
        public string Href { get; set; }

        [Description("同一層Menu的排序碼")]
        public string SortNum { get; set; }

        [Description("類別")]
        public string DebtType { get; set; }

        [Description("新增者帳號")]
        public string Create_User { get; set; }

        [Description("新增日期")]
        public string Create_Date { get; set; }

        [Description("新增時間")]
        public string Create_Time { get; set; }

        [Description("最後修改者帳號")]
        public string LastUpdate_User { get; set; }

        [Description("最後修改日期")]
        public string LastUpdate_Date { get; set; }

        [Description("最後修改時間")]
        public string LastUpdate_Time { get; set; }
    }
}

Transfer/ViewModels/SetAssessmentViewModel.cs
using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Transfer.ViewModels
{
    public class SetAssessmentViewModel
    {
        [Description("群組編號")]
        public string Group_Product_Code { get; set; }

        [Description("群組名稱")]
        public string Group_Product_Name { get; set; }

        [Description("資料表編號")]
        public string Table_Id { get; set; }

        [Description("覆核/呈送(人員帳號)")]
        public string User_Account { get; set; }

        [Description("覆核/呈送(人員名稱)")]
        public string User_Name { get; set; }
    }
}

Transfer/ViewModels/TaskScheduleViewModel.cs
using System.ComponentModel;

namespace Transfer.ViewModels
{
    public class TaskScheduleViewModel
    {
        [Description("觸發排程")]
        public string Trigger_Task { get; set; }
        [Description("報導日/基準日")]
        public string ReportDate { get; set; }
        [Description("資料版本")]
        public string Version { get; set; }
        [Description("資料表名稱")]
        public string File_Name { get; set; }
        [Description("成功/失敗")]
        public string TransferType { get; set; }
        [Description("開始日期")]
        public string Create_Date { get; set; }
        [Description("開始時間")]
        public string Create_Time { get; set; }
        [Description("結束日期")]
        public string End_Date { get; set; }
        [Description("結束時間")]
        public string End_Time { get; set; }
    }
}

Transfer/Controllers/SystemForITController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Transfer.Models;
using Transfer.Models.Interface;
using Transfer.Models.Repository;
using Transfer.Utility;
using Transfer.ViewModels;
using static Transfer.Enum.Ref;

namespace Transfer.Controllers
{
    public class SystemForITController : CommonForITController
    {
        private ISystemForITRepository SystemForITRepository;
        private string adminAccount;

        public SystemForITController()
        {
            this.SystemForITRepository = new SystemForITRepository();
            this.adminAccount = "";
        }

        /// <summary>
        /// 設定主頁 (預留)
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 設定 Account 的權限
        /// </summary>
        /// <returns></returns>
        public ActionResult SetAccount()
        {
            var jqgridInfo = new AccountViewModel().TojqGridData(null, null, true);
            ViewBag.jqgridColNames = jqgridInfo.colNames;
            ViewBag.jqgridColModel = jqgridInfo.colModel;
            ViewBag.debt = GetDebtSelectOption();
            return View();
        }

        /// <summary>
        /// 設定 Menu 的權限
        /// </summary>
        /// <returns></returns>
        public ActionResult SetMenu()
        {
            ViewBag.users = new SelectList(
                 SystemForITRepository.getUser("menu", false, adminAccount)
                 .Select(x => new { Text = x.Item2, Value = x.Item1 }), "Value", "Text");
            return View();
        }

        /// <summary>
        /// 設定 Assessment 的權限
        /// </summary>
        /// <returns></returns>
        public ActionResult SetAssessment()
        {
            ViewBag.productCode = new SelectList(
                 SystemForITRepository.getProductCode(adminAccount)
                 .Select(x => new { Value = x.Item1, Text = x.Item2 }), "Value", "Text");
            return View();
        }

        /// <summary>
        /// 排程重啟
        /// </summary>
        /// <returns></returns>
        public ActionResult TaskSchedule()
        {
            return View();
        }

        /// <summary>
        /// 帳號使用紀錄
        /// </summary>
        /// <returns></returns>
        public ActionResult AccountLog()
        {
            List<RadioButton> data = new List<RadioButton>();
            data.Add(new RadioButton() { Name = "Effective", Checked = true, Value = "只查詢有效帳號", Id = "Effective" });
            data.Add(new RadioButton() { Name = "Effective", Checked = false, Value = "全部查詢(包含失效)", Id = "EffectiveAll" });
            ViewBag.radio = data;
            data = new List<RadioButton>();
            data.Add(new RadioButton() { Name = "Range", Checked = true, Value = "今天", Id = "1" });
            data.Add(new RadioButton() { Name = "Range", Checked = false, Value = "一周內", Id = "7" });
            data.Add(new RadioButton() { Name = "Range", Checked = false, Value = "全部查詢", Id = "All" });
            ViewBag.radio2 = data;
            ViewBag.users = new SelectList(SystemForITRepository.getUser("log", false, adminAccount)
                   .Select(x => new { Text = x.Item2, Value = x.Item1 }), "Value", "Text");
            return View();
        }

        /// <summary>
        /// 選單類別維護
        /// </summary>
        /// <returns></returns>
        public ActionResult MenuMain()
        {
            return View();
        }

        /// <summary>
        /// 選單明細維護
        /// </summary>
        /// <returns></returns>
        public ActionResult MenuSub()
        {
            List<SelectOption> selectOption = new List<SelectOption>();
            selectOption.Add(new SelectOption() { Text = "", Value = "" });
            selectOption.AddRange((SystemForITRepository.getMenuMainAll().Item2)
                                    .Select(x => new SelectOption()
                                    { Text = (x.Menu + "：" + x.Menu_Detail), Value = x.Menu }));
            ViewBag.MenuClass = new SelectList(selectOption, "Value", "Text");

            selectOption = new List<SelectOption>() {
                                              new SelectOption() { Text = "", Value = "" },
                                              new SelectOption() { Text = "A：All(所有權限)", Value = "A" },
                                              new SelectOption() { Text = "B：Bonds(債券)", Value = "B" },
                                              new SelectOption() { Text = "M：Mortgage(房貸)", Value = "M" }
                                           };
            ViewBag.DebtType = new SelectList(selectOption, "Value", "Text");

            return View();
        }

        public JsonResult changeEffective(bool searchAll)
        {
            return Json(SystemForITRepository.getUser("log", searchAll, adminAccount));
        }

        /// <summary>
        /// 抓取使用者的 menu 設定
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public JsonResult GetUser(string name)
        {
            MSGReturnModel result = new MSGReturnModel();
            List<CheckBoxListInfo> data
                = SystemForITRepository.getMenu(name);
            if (data.Any())
            {
                result = new MSGReturnModel()
                {
                    RETURN_FLAG = true,
                    Datas = Json(Extension.CheckBoxString("menuSet", data, null, 3).ToString())
                };
            }
            else
                result = new MSGReturnModel()
                {
                    RETURN_FLAG = false,
                    DESCRIPTION = Message_Type.not_Find_Any.GetDescription()
                };
            return Json(result);
        }

        /// <summary>
        /// 儲存使用者的menu設定
        /// </summary>
        /// <param name="data">menu Data</param>
        /// <param name="userName"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SaveMenu(List<CheckBoxListInfo> data, string userName)
        {
            MSGReturnModel result = SystemForITRepository.saveMenu(data, userName);
            return Json(result);
        }

        /// <summary>
        /// 儲存帳號
        /// </summary>
        /// <param name="action">前端動作</param>
        /// <param name="account">帳號</param>
        /// <param name="pwd">密碼</param>
        /// <param name="name">暱稱</param>
        /// <param name="adminFlag">是否為管理者</param>
        /// <param name="loginFlag">登入狀態</param>
        /// <param name="debtFlag">權限類別</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SaveAccount(string action, string account, string pwd, string name, string adminFlag, string loginFlag, string debtFlag)
        {
            MSGReturnModel result = new MSGReturnModel();
            result.RETURN_FLAG = false;
            if (account.IsNullOrWhiteSpace() ||
                !EnumUtil.GetValues<Action_Type>().Select(x => x.ToString()).Contains(action))
            {
                result.DESCRIPTION = Message_Type.parameter_Error.GetDescription();
                return Json(result);
            }
            IFRS9_User data = new IFRS9_User();
            data.User_Account = account.Trim();
            data.User_Name = name == null ? string.Empty : name.Trim();
            if (action == Action_Type.Edit.ToString())
            {
                data.AdminFlag = adminFlag == "Y" ? true : false;
                data.LoginFlag = loginFlag == "Y" ? true : false;
                data.DebtType = debtFlag;
                if (!pwd.IsNullOrWhiteSpace())
                    data.User_Password = pwd.Trim();
            }
            if (action == Action_Type.Add.ToString())
            {
                data.User_Password = pwd.Trim();
                data.DebtType = debtFlag;
                data.AdminFlag = adminFlag == "Y" ? true : false;
            }
            result = SystemForITRepository.saveAccount(action, data);
            if (result.RETURN_FLAG)
            {
                SetCacheData(SystemForITRepository.getAccount(string.Empty,""));
            }
            return Json(result);
        }

        /// <summary>
        /// 查詢帳號
        /// </summary>
        /// <param name="account">查詢的條件</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SearchAccount(string account)
        {
            MSGReturnModel result = new MSGReturnModel();
            result.RETURN_FLAG = false;
            result.DESCRIPTION = Message_Type.not_Find_Any.GetDescription();
            List<AccountViewModel> datas =
                SystemForITRepository.getAccount(account, adminAccount);
            if (datas.Any())
            {
                SetCacheData(datas);
                result.RETURN_FLAG = true;
            }
            return Json(result);
        }

        /// <summary>
        /// 查詢帳號使用紀錄
        /// </summary>
        /// <param name="account">查詢的條件</param>
        /// <param name="type">查詢的log,User=IFRS9_User_Log,Browser=IFRS9_Browse_Log,Event=IFRS9_Event_Log</param>
        /// <param name="range">查詢的範圍 今天,7天,全部 (tpye = user 使用)</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult SearchAccountLog(AccountLogViewModel model, string type, string range)
        {
            MSGReturnModel result = new MSGReturnModel();
            result.RETURN_FLAG = false;
            result.DESCRIPTION = Message_Type.not_Find_Any.GetDescription();
            List<AccountLogViewModel> datas = SystemForITRepository.getAccountLog(model, type, range);
            if (datas.Any())
            {
                SetCacheDataInAccountLog(datas, type);
                result.RETURN_FLAG = true;
            }
            return Json(result);
        }

        /// <summary>
        /// 查詢信評

Transfer/Views/SystemForIT/Index.cshtml
@{
    ViewBag.Menu = "SystemMain";
    ViewBag.SubMenu = "System0Sub";
    ViewBag.Title = "設定";
    Layout = "~/Views/Shared/_LayoutForIT.cshtml";
}
<div class="container" id="main">
    <div class="row main_hand">
        <div class="col-md-12 main_hand_div">
            <table>
                <tr>
                    <td style="font-size:20px">
                        IFRS9 管理介面
                    </td>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row main_body" style="overflow:auto;height:100%">
        <div class="col-md-12">
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {

    });
</script>

Transfer/Views/SystemForIT/SetAccount.cshtml
@using Transfer.Utility;
@using Transfer.Enum;
@{
    ViewBag.Menu = "SystemMain";
    ViewBag.SubMenu = "SystemAccountSub";
    ViewBag.Title = "設定帳號";
    Layout = "~/Views/Shared/_LayoutForIT.cshtml";
}
<div class="container" id="main">
    <div class="row main_hand">
        <div class="col-md-12 main_hand_div">
            <table>
                <tr>
                    <td width="450px">
                        <label>帳號查詢 : </label>
                        <input type="text" id="account" name="account" style="width:300px">
                    </td>
                    <td>
                        <input type="button" class="btn btn-primary" value="查詢" id="btnSearch" />
                    </td>
                </tr>
                <tr>
                    <td colspan="2" style="padding-top:10px">
                        <input type="button" class="btn btn-primary" value="新增" id="btnAdd" />
                    </td>
                </tr>
            </table>
            <i class="fa fa-exclamation-circle title" style="font-size:24px;"
               alt="說明：
沒有輸入查詢條件時為全部查詢"></i>
        </div>
    </div>
    <div class="row main_body" style="overflow:auto;height:100%">
        <div class="col-md-12">
            <div class="viewDetail">
                <div id="jqgridDiv" class="jqd">
                </div>
            </div>
        </div>
    </div>
    <div id="AccountDialog"></div>
</div>
<script type="text/javascript">
    var _debt1 = @Html.Raw(Json.Encode(ViewBag.debt));
    $(function () {
        //#region 註冊URL
        var url = {};
        url.searchAccount = '@Url.Action("SearchAccount", "SystemForIT")';
        url.getAccount = '@Url.Action("GetCacheData", "SystemForIT")';
        url.saveAccount = '@Url.Action("SaveAccount", "SystemForIT")';
        //#endregion 註冊URL

        //#region 共用參數
        var _debt = @Html.Raw(Json.Encode(ViewBag.debt));
        var dialogId = 'AccountDialog';
        var dialogformId = dialogId + 'Form';
        var accountId = dialogId + 'account';
        var passwordId = dialogId + 'password';
        var passwordConfirmId = dialogId + 'passwordConfirm';
        var nameId = dialogId + 'name';
        var adminFlagId = dialogId + 'adminFlag';
        var debtFlagId = dialogId + 'debtFlag';
        var loginFlagId = dialogId + 'loginFlag';
        var saveId = dialogId + 'btnSave';
        var deleteId = dialogId + 'btnDelete';
        //#endregion 共用參數

        //#region 產生 dialog
        var obj = [
           { 'name': 'account', 'type': 'string', 'title': '使用者帳號', 'max': '30', 'req': 'true' },
           { 'name': 'password', 'type': 'string', 'title': '使用者密碼', 'max': '30', 'req': 'true' },
           { 'name': 'passwordConfirm', 'type':'string', 'title': '確認密碼' },
           { 'name': 'name', 'type': 'string', 'title': '使用者名稱', 'max': '30' },
           { 'name': 'adminFlag', 'type': 'selectOption', 'title': '是否為管理員'},
           { 'name': 'debtFlag', 'type': 'selectOption', 'title': '類別'},
           { 'name': 'loginFlag', 'type': 'selectOption', 'title': '是否登入中'}
        ]
        jqgridCustom.createDialog(dialogId, obj);
        //#endregion 產生 dialog

        //#region 註冊click事件
        $('input:button').each(function () {
            var id = $(this).attr('id');
            switch (id) {
                case 'btnSearch':
                    $("#" + id).on('click', function () { AccountSearch() });
                    break;
                case 'btnAdd':
                    $("#" + id).on('click', function () { dialogOpen('@Ref.Action_Type.Add.ToString()') });
                    break;
            }
        })
        //#endregion 註冊click事件

        //#region Search Account
        function AccountSearch()
        {
            clearJqgrid();
            var title = '@Ref.Table_Type.UserTable.GetDescription()'; //標頭
            $.ajax({
                type: "POST",
                data: JSON.stringify({
                    account: $('#account').val()
                }),
                dataType: "json",
                url: url.searchAccount,
                contentType: 'application/json',
            })
            .done(function (result) {
                if (result.RETURN_FLAG) {
                    createJqgrid("list1", "pager1", title);
                }
                else {
                    customerUtility.alert(result.DESCRIPTION,'e');
                }
            });
        }
        //#endregion Search Account

        //#region clearJqgrid (清除JqGrid)
        function clearJqgrid() {
            $('#jqgridDiv').children().remove();
        }
        //#endregion clearJqgrid

        //#region createJqgrid (建立JqGrid套件)
        //listId (Jqgrid產生table的ID)
        //pagerId (下方產生筆數的ID)
        //title (標題)
        function createJqgrid(listId, pagerId, title) {
            $('#jqgridDiv').append('<table id="' + listId + '"></table>');
            $('#jqgridDiv').append('<div id="' + pagerId + '"></div>');
            $("#" + listId).jqGrid({
                url: url.getAccount,
                datatype: "json",
                mtype: "POST",
                postData:
                {
                    //type: "Db",
                },
                jsonReader:
                {
                    repeatitems: false,
                },
                colNames: @Html.Raw(Json.Encode(ViewBag.jqgridColNames)),
                colModel: @Html.Raw(Json.Encode(ViewBag.jqgridColModel)),
                 rowNum: jqgridCustom.rowNum(), //一頁筆數
                rowList: jqgridCustom.rowList(), //設定一頁幾筆
                pager: '#' + pagerId,
                height: jqgridCustom.getHeight(),
                width: jqgridCustom.getwidth(),
                caption: title, //標題
                viewrecords: true, //顯示總數
                shrinkToFit: false,
                contentType: "application/json",
                loadComplete: function () {
                    var table = $(this);
                    jqgridCustom.updatePagerIcons(table);
                    jqgridCustom.randerAction(listId, 'Account',actfun);
                }
            });
            $("#" + listId).jqGrid('navGrid', '#' + pagerId, { edit: false, add: false, del: false });
        }
        //#endregion createJqgrid

        var actfun = {};
        actfun.Edit = function(i)
        {
            dialogOpen('@Ref.Action_Type.Edit.ToString()',i);
        }
        actfun.Dele = function(i)
        {
            dialogOpen('@Ref.Action_Type.Dele.ToString()',i);
        }
        actfun.View = function(i)
        {
            dialogOpen('@Ref.Action_Type.View.ToString()',i);
        }

        function dialogOpen(type,rowid)
        {
            var title = '';
            $('#'+saveId+',#'+deleteId).hide();
            $('#'+loginFlagId).show();
            $("#"+adminFlagId+" option").remove();
            $("#"+loginFlagId+" option").remove();
            $("#"+debtFlagId+" option").remove();
            var optionObj = [];
            optionObj.push({value:"N",text:"N"})
            optionObj.push({value:"Y",text:"Y"})
            customerUtility.addoption(adminFlagId,optionObj);
            customerUtility.addoption(loginFlagId,optionObj);
            customerUtility.addoption(debtFlagId,_debt);
            $('#'+accountId).attr('disabled',false);
            $('#'+nameId).attr('disabled',false);
            $('#'+adminFlagId).attr('disabled',false);
            $('#'+loginFlagId).attr('disabled',false);
            $('#'+debtFlagId).attr('disabled',false);
            if(type == '@Ref.Action_Type.Add.ToString()')
            {
                title = '@Ref.Action_Type.Add.GetDescription()';
                $('#'+passwordId+'tr').show();
                $('#'+passwordConfirmId+'tr').show();
                $('#'+saveId).show();
                $('#'+loginFlagId+'tr').hide();
                $('#'+accountId).val('');
                $('#'+passwordId).val('');
                $('#'+passwordConfirmId).val('');
                $('#'+nameId).val('');
                $('#'+saveId).off('click');
                $('#'+saveId).on('click',function(){
                    dialogSave(type);
                });
            }
            else if(type == '@Ref.Action_Type.Edit.ToString()')
            {
                title = '@Ref.Action_Type.Edit.GetDescription()';
                $('#'+passwordId+'tr').show();
                $('#'+passwordConfirmId+'tr').show();
                $('#'+saveId).show();
                dialogSetData(rowid);
                $('#'+accountId).attr('disabled',true);
                //$('#'+adminFlagId).attr('disabled',true);
                $('#'+saveId).off('click');
                $('#'+saveId).on('click',function(){
                    dialogSave(type);
                });
            }
            else if(type == '@Ref.Action_Type.Dele.ToString()')
            {
                title = '@Ref.Action_Type.Dele.GetDescription()';
                $('#'+passwordId+'tr').hide();
                $('#'+passwordConfirmId+'tr').hide();
                $('#'+deleteId).show();
                dialogSetData(rowid);
                $('#'+accountId).attr('disabled',true);
                $('#'+nameId).attr('disabled',true);
                $('#'+adminFlagId).attr('disabled',true);
                $('#'+loginFlagId).attr('disabled',true);
                $('#'+debtFlagId).attr('disabled',true);
                $('#'+deleteId).off('click');
                $('#'+deleteId).on('click',function(){
                    dialogSave(type);
                });
            }
            else if(type == '@Ref.Action_Type.View.ToString()')
            {
                title = '@Ref.Action_Type.View.GetDescription()';
                $('#'+passwordId+'tr').hide();
                $('#'+passwordConfirmId+'tr').hide();
                dialogSetData(rowid);
                $('#'+accountId).attr('disabled',true);
                $('#'+nameId).attr('disabled',true);
                $('#'+adminFlagId).attr('disabled',true);
                $('#'+loginFlagId).attr('disabled',true);
                $('#'+debtFlagId).attr('disabled',true);
            }
            $("#" + dialogId).dialog({
                title: title,
                position: { my: "center", at: "center", of: window },
            });
            $("#" + dialogId).dialog("open");
            $('#'+dialogformId).validate().resetForm();
        }

        function dialogSetData(rowid)
        {
            rowid = rowid || 0;
            //清空
            $('#'+accountId).val('');
            $('#'+passwordId).val('');
            $('#'+passwordConfirmId).val('');
            $('#'+nameId).val('');
            if(rowid > 0)
            {
                var data = $("#list1").getRowData(rowid);
                //set value
                $('#'+accountId).val(data.User_Account);
                $('#'+nameId).val(data.User_Name);
                $('#'+adminFlagId).val(data.AdminFlag).change();
                $('#'+loginFlagId).val(data.LoginFlag).change();
                $('#'+debtFlagId).val(data.DebtFlag.split(':',1)[0]).change();
            }
        }

        //#region save Account
        function dialogSave(action)
        {
            if(action == '@Ref.Action_Type.Edit.ToString()' || $('#'+dialogformId).valid())
            {
                let flag = false;
                if(action =='@Ref.Action_Type.Dele.ToString()')
                {
                    if(!confirm("確定刪除?"))
                    {
                        return false;
                    }
                    flag = true;
                }
                else
                {
                    if($('#'+passwordId).val() !== $('#'+passwordConfirmId).val())
                    {
                        customerUtility.alert('密碼與確認密碼不同,請重新輸入!','w');
                        $('#'+passwordId).val('');
                        $('#'+passwordConfirmId).val('');
                        return false;
                    }
                    flag = true;
                }
                if(flag)
                {
                    $.ajax({
                        type: "POST",
                        data: JSON.stringify({
                            action: action, //action
                            account: $('#'+accountId).val(),
                            pwd: $('#'+passwordId).val(),
                            name : $('#'+nameId).val(),
                            adminFlag: $('#'+adminFlagId).val(),
                            loginFlag: $('#'+loginFlagId).val(),
                            debtFlag: $('#'+debtFlagId).val()
                        }),
                        dataType: "json",
                        url: url.saveAccount,
                        contentType: 'application/json',
                    })
                    .done(function (result) {
                        if (result.RETURN_FLAG) {
                            $("#" + dialogId).dialog("close");
                            customerUtility.alert(result.DESCRIPTION,'s');
                            clearJqgrid();
                            createJqgrid("list1", "pager1", '@Ref.Table_Type.UserTable.GetDescription()');
                        }
                        else {
                            customerUtility.alert(result.DESCRIPTION,'e');
                        }
                    });
                }
            }
        }
        //#endregion save Account

    });
</script>