Transfer/ViewModels/D70ViewModel.cs
using System.ComponentModel;

namespace Transfer.ViewModels
{
    public class D70ViewModel
    {
        [Description("規則編號")]
        public string Rule_ID { get; set; }

        [Description("基本要件評估時點(代碼)")]
        public string Basic_Pass_Check_Point { get; set; }

        [Description("基本要件評估時點")]
        public string Basic_Pass_Check_Point_Name { get; set; }

        [Description("基本要件是否通過(代碼)")]
        public string Basic_Pass { get; set; }

        [Description("基本要件是否通過")]
        public string Basic_Pass_Name { get; set; }

        [Description("信評評估時點(代碼)")]
        public string Rating_Check_Point { get; set; }

        [Description("信評評估時點")]
        public string Rating_Check_Point_Name { get; set; }

        [Description("報導日信評門檻")]
        public string Rating_Threshold { get; set; }

        [Description("信評主標尺資料年度")]
        public string Data_Year { get; set; }

        [Description("報導日信評門檻-對應評等主標尺_原始 ")]
        public string Rating_Threshold_Map_Grade { get; set; }

        [Description("報導日信評門檻-對應評等主標尺_調整後")]
        public string Rating_Threshold_Map_Grade_Adjust { get; set; }

        [Description("是否包含(報導日信評門檻)(代碼)")]
        public string Including_Ind_0 { get; set; }

        [Description("是否包含(報導日信評門檻)")]
        public string Including_Ind_0_Name { get; set; }

        [Description("範圍 _以上/以下(報導日信評門檻)(代碼)")]
        public string Apply_Range_0 { get; set; }

        [Description("範圍 _以上/以下(報導日信評門檻)")]
        public string Apply_Range_0_Name { get; set; }

        [Description("報導日信評區間_from")]
        public string Rating_from { get; set; }

        [Description("報導日信評區間_from-對應評等主標尺_原始")]
        public string Rating_from_Map_Grade { get; set; }

        [Description("報導日信評區間_from-對應評等主標尺_調整後")]
        public string Rating_from_Map_Grade_Adjust { get; set; }

        [Description("報導日信評區間_To")]
        public string Rating_To { get; set; }

        [Description("報導日信評區間_To-對應評等主標尺_原始")]
        public string Rating_To_Map_Grade { get; set; }

        [Description("報導日信評區間_To-對應評等主標尺_調整後")]
        public string Rating_To_Map_Grade_Adjust { get; set; }

        [Description("未實現累計損失月數")]
        public string Value_Change_Months { get; set; }

        [Description("是否包含(未實現累計損失月數)(代碼)")]
        public string Including_Ind_1 { get; set; }

        [Description("是否包含(未實現累計損失月數)")]
        public string Including_Ind_1_Name { get; set; }

        [Description("範圍 _以上/以下(未實現累計損失月數)(代碼)")]
        public string Apply_Range_1 { get; set; }

        [Description("範圍 _以上/以下(未實現累計損失月數)")]
        public string Apply_Range_1_Name { get; set; }

        [Description("信用利差拓寬累積月數")]
        public string Spread_Change_Months { get; set; }

        [Description("是否包含(信用利差拓寬累積月數)(代碼)")]
        public string Including_Ind_2 { get; set; }

        [Description("是否包含(信用利差拓寬累積月數)")]
        public string Including_Ind_2_Name { get; set; }

        [Description("範圍 _以上/以下(信用利差拓寬累積月數)(代碼)")]
        public string Apply_Range_2 { get; set; }

        [Description("範圍 _以上/以下(信用利差拓寬累積月數)")]
        public string Apply_Range_2_Name { get; set; }

        [Description("規則設定者帳號")]
        public string Rule_setter { get; set; }

        [Description("規則設定者名稱")]
        public string Rule_setter_Name { get; set; }

        [Description("規則編輯日期")]
        public string Rule_setting_Date { get; set; }

        [Description("複核人員帳號")]
        public string Auditor { get; set; }

        [Description("複核人員名稱")]
        public string Auditor_Name { get; set; }

        [Description("複核日期")]
        public string Audit_Date { get; set; }

        [Description("處理狀態(代碼)")]
        public string Status { get; set; }

        [Description("處理狀態")]
        public string Status_Name { get; set; }

        [Description("Rule_desc")]
        public string Rule_desc { get; set; }

        [Description("使用狀態(代碼)")]
        public string IsActive { get; set; }

        [Description("使用狀態")]
        public string IsActive_Name { get; set; }
    }
}

Transfer/Controllers/D7Controller.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Transfer.Infrastructure;
using Transfer.Models;
using Transfer.Models.Interface;
using Transfer.Models.Repository;
using Transfer.Utility;
using Transfer.ViewModels;
using static Transfer.Enum.Ref;

namespace Transfer.Controllers
{
    [LogAuth]
    public class D7Controller : CommonController
    {
        private IA5Repository A5Repository;
        private ID6Repository D6Repository;
        private ID7Repository D7Repository;
        List<SelectOption> selectOptionYN;
        List<SelectOption> selectOptionRange;
        List<SelectOption> selectOptionStatus;
        SystemRepository systemRepository = new SystemRepository();
        private string groupProductCode = Assessment_Type.B.GetDescription();

        public D7Controller()
        {
            this.A5Repository = new A5Repository();
            this.D6Repository = new D6Repository();
            this.D7Repository = new D7Repository();

            selectOptionYN = new List<SelectOption>() {
                                                  new SelectOption() { Text = "", Value = "" },
                                                  new SelectOption() { Text = "Y：是", Value = "Y" },
                                                  new SelectOption() { Text = "N：否", Value = "N" }
                                              };

            selectOptionRange = new List<SelectOption>() {
                                                  new SelectOption() { Text = "", Value = "" },
                                                  new SelectOption() { Text = "1：以上", Value = "1" },
                                                  new SelectOption() { Text = "0：以下", Value = "0" }
                                              };

            ProcessStatusList psl = new ProcessStatusList();
            selectOptionStatus = psl.statusOption;
            selectOptionStatus.Insert(0, new SelectOption() { Text = "", Value = "" });
        }

        // GET: D7Controller
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// D70-觀察名單參數檔
        /// </summary>
        /// <returns></returns>
        [UserAuth]
        public ActionResult D70()
        {
            List<SelectOption> selectOptionCheckPoint = new List<SelectOption>() {
                                                                  new SelectOption() { Text = "", Value = "" },
                                                                  new SelectOption() { Text = "-2：上上個月報導日", Value = "-2" },
                                                                  new SelectOption() { Text = "0：本月報導日", Value = "0" }
                                                                };
            ViewBag.BasicPassCheckPoint = new SelectList(selectOptionCheckPoint, "Value", "Text");

            List<SelectOption> selectOptionBasicPass = new List<SelectOption>() {
                                                       new SelectOption() { Text = "", Value = "" },
                                                       new SelectOption() { Text = "Y：是", Value = "Y" },
                                                       new SelectOption() { Text = "N：否", Value = "N" },
                                                       new SelectOption() { Text = "-999", Value = "-999" }
                                                     };
            ViewBag.BasicPass = new SelectList(selectOptionBasicPass, "Value", "Text");

            ViewBag.RatingCheckPoint = new SelectList(selectOptionCheckPoint, "Value", "Text");

            List<SelectOption> selectOptionA52 = new List<SelectOption>();
            selectOptionA52.Add(new SelectOption() { Text = "", Value = "" });
            selectOptionA52.AddRange((A5Repository.getA52("SP").Item2)
                           .Select(x => new SelectOption() { Text = x.Rating, Value = x.Rating }));
            selectOptionA52.Add(new SelectOption() { Text = "-999", Value = "-999" });
            ViewBag.A52 = new SelectList(selectOptionA52, "Value", "Text");

            ViewBag.IncludingInd0 = new SelectList(selectOptionYN, "Value", "Text");
            ViewBag.IncludingInd1 = new SelectList(selectOptionYN, "Value", "Text");
            ViewBag.IncludingInd2 = new SelectList(selectOptionYN, "Value", "Text");

            ViewBag.ApplyRange0 = new SelectList(selectOptionRange, "Value", "Text");
            ViewBag.ApplyRange1 = new SelectList(selectOptionRange, "Value", "Text");
            ViewBag.ApplyRange2 = new SelectList(selectOptionRange, "Value", "Text");

            ViewBag.Status = new SelectList(selectOptionStatus, "Value", "Text");

            if (getAssessment(groupProductCode, "D70", SetAssessmentType.Presented)
                .Any(x => x.User_Account.Contains(AccountController.CurrentUserInfo.Name)))
            {
                ViewBag.IsSender = "Y";
            }
            else
            {
                ViewBag.IsSender = "N";
            }

            List<SelectOption> selectOption = new List<SelectOption>();
            selectOption.Add(new SelectOption() { Text = "", Value = "" });
            selectOption.AddRange(getAssessment(groupProductCode, "D70", SetAssessmentType.Auditor)
                                 .Select(x => new SelectOption()
                                 { Text = (x.User_Name), Value = x.User_Account }));

            ViewBag.Auditor = new SelectList(selectOption, "Value", "Text");

            ViewBag.UserAccount = AccountController.CurrentUserInfo.Name;

            IsActiveList ial = new IsActiveList();
            selectOption = ial.isActiveOption;
            selectOption.Insert(0, new SelectOption() { Text = "", Value = "" });
            ViewBag.IsActive = new SelectList(selectOption, "Value", "Text");
            ViewBag.A51Year = D7Repository.GetA51Year();
            return View();
        }

        /// <summary>
        /// D71-預警名單參數檔
        /// </summary>
        /// <returns></returns>
        [UserAuth]
        public ActionResult D71()
        {
            List<SelectOption> selectOptionCheckPoint = new List<SelectOption>() {
                                                                  new SelectOption() { Text = "", Value = "" },
                                                                  new SelectOption() { Text = "-1：上個月報導日", Value = "-1" },
                                                                  new SelectOption() { Text = "0：本月報導日", Value = "0" }
                                                                };
            ViewBag.BasicPassCheckPoint = new SelectList(selectOptionCheckPoint, "Value", "Text");

            List<SelectOption> selectOptionBasicPass = new List<SelectOption>() {
                                                       new SelectOption() { Text = "", Value = "" },
                                                       new SelectOption() { Text = "Y：是", Value = "Y" },
                                                       new SelectOption() { Text = "N：否", Value = "N" },
                                                       new SelectOption() { Text = "-999", Value = "-999" }
                                                     };
            ViewBag.BasicPass = new SelectList(selectOptionBasicPass, "Value", "Text");

            ViewBag.RatingCheckPoint = new SelectList(selectOptionCheckPoint, "Value", "Text");

            List<SelectOption> selectOptionA52 = new List<SelectOption>();
            selectOptionA52.Add(new SelectOption() { Text = "", Value = "" });
            selectOptionA52.AddRange((A5Repository.getA52("SP").Item2)
                           .Select(x => new SelectOption() { Text = x.Rating, Value = x.Rating }));
            selectOptionA52.Add(new SelectOption() { Text = "-999", Value = "-999" });
            ViewBag.A52 = new SelectList(selectOptionA52, "Value", "Text");

            ViewBag.IncludingInd0 = new SelectList(selectOptionYN, "Value", "Text");
            ViewBag.IncludingInd1 = new SelectList(selectOptionYN, "Value", "Text");
            ViewBag.IncludingInd2 = new SelectList(selectOptionYN, "Value", "Text");

            ViewBag.ApplyRange0 = new SelectList(selectOptionRange, "Value", "Text");
            ViewBag.ApplyRange1 = new SelectList(selectOptionRange, "Value", "Text");
            ViewBag.ApplyRange2 = new SelectList(selectOptionRange, "Value", "Text");

            ViewBag.Status = new SelectList(selectOptionStatus, "Value", "Text");

            if (getAssessment(groupProductCode, "D71", SetAssessmentType.Presented)
                .Any(x => x.User_Account.Contains(AccountController.CurrentUserInfo.Name)))
            {
                ViewBag.IsSender = "Y";
            }
            else
            {
                ViewBag.IsSender = "N";
            }

            List<SelectOption> selectOption = new List<SelectOption>();
            selectOption.Add(new SelectOption() { Text = "", Value = "" });
            selectOption.AddRange(getAssessment(groupProductCode, "D71", SetAssessmentType.Auditor)
                                 .Select(x => new SelectOption()
                                 { Text = (x.User_Name), Value = x.User_Account }));

            ViewBag.Auditor = new SelectList(selectOption, "Value", "Text");

            ViewBag.UserAccount = AccountController.CurrentUserInfo.Name;

            IsActiveList ial = new IsActiveList();
            selectOption = ial.isActiveOption;
            selectOption.Insert(0, new SelectOption() { Text = "", Value = "" });
            ViewBag.IsActive = new SelectList(selectOption, "Value", "Text");
            ViewBag.A51Year = D7Repository.GetA51Year();
            return View();
        }

        /// <summary>
        /// D72-SMF分群設定檔
        /// </summary>
        /// <returns></returns>
        [UserAuth]
        public ActionResult D72Detail()
        {

Transfer/Views/D7/D72Detail.cshtml
@using Transfer.Utility;
@using Transfer.Enum;
@{
    ViewBag.Menu = "D6Main";
    ViewBag.SubMenu = "D72Sub";
    ViewBag.Title = "D72(SMF分群設定檔)";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container" id="main">
    <div class="row main_hand">
        <div class="col-md-12 main_hand_div">
            <form id="myForm">
                <table>
                    <tr>
                        <td style="">
                            <label>選擇動作 : </label>
                            @Html.DropDownList("action",
                           (SelectList)ViewBag.action,
                            new { @class = "form-control", @style = "display:inline-block" })
                        </td>
                    </tr>
                    <tr class="action search">
                        <td style="padding-top:10px;">
                            <input type="button" class="btn btn-primary" value="查詢" id="btnD72Search" style="" />
                        </td>
                    </tr>
                </table>
            </form>
            <table>
                <tr class="action upload" style="display:none">
                    <td style="padding-top:10px;">
                        @using (Ajax.BeginForm("UploadD72", "D7",
                         new AjaxOptions { HttpMethod = "POST" },
                         new { enctype = "multipart/form-data", @id = "form0" }))
                        {
                            <input type="file" name="file" class="filestyle" data-buttonName="btn-primary" data-buttonText="轉檔檔案" style="margin-right:10px" />
                        }
                    </td>
                    <td style="padding-top:10px;">
                        <input type="button" class="btn btn-primary" style="margin-right:10px" value="資料上傳" id="fileSubmit" />
                        <input type="button" class="btn btn-primary" value="轉檔" id="btnTransfer" disabled />
                    </td>
                </tr>
            </table>
        <i class="fa fa-exclamation-circle title" style="font-size:24px;"
           alt="說明：
"></i>
        </div>
    </div>
    <div class="row main_body" style="overflow:auto;height:100%">
        <div class="col-md-12">
            <div class="viewDetail">
                <div id="jqgridDiv" class="jqd">
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        //#region 註冊URL
        var url = {};
        url.type = '@Ref.Table_Type.D72.ToString()';
        url.search = '@Url.Action("GetD72Data", "D7")';
        url.getDbData = '@Url.Action("GetDefaultCacheData", "D7")';
        url.transfer = '@Url.Action("TransferD72", "D7")';
        //#endregion 註冊URL

        //#region 刪除verified
        function removeVerified() {
            $("#myForm").validate().resetForm();
        }
        //#endregion 刪除verified

        $('#action').on('change', function () {
            clearJqgrid();
            $('#btnTransfer').prop('disabled', true);
            $('.action').hide();
            var opencls = $(this).val();
            $('.' + opencls).show();
        });

        //#region 註冊click事件
        $('input:button').each(function () {
            var id = $(this).attr('id');
            switch (id) {
                case 'btnD72Search':
                    $('#' + id).on('click', function () { D72Search() });
                    break;
                case 'fileSubmit':
                    $('#' + id).click(fileSubmitFunction);
                    break;
                case 'btnTransfer':
                    $('#' + id).click(transfer);
                    break;
            }
        })
        //#endregion 註冊click事件

        function D72Search(id) {
            if ($('#myForm').valid()) {
                clearJqgrid();
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: url.search,
                    contentType: 'application/json',
                })
                .done(function (result) {
                    if (result.RETURN_FLAG) {
                        createJqgrid(
                            "list1",
                            "pager1",
                            '@Ref.Table_Type.D72.tableNameGetDescription()',
                            url.type + "Db"
                            );
                    }
                    else
                        customerUtility.alert(result.DESCRIPTION,'e');
                })
            }
        }

        //#region 資料上傳(Excel 資料寫入 local sql)
        function transfer() {
            $.ajax({
                type: "POST",
                url: url.transfer,
                contentType: 'application/json'
            })
            .done(function (result) {
                if (result.RETURN_FLAG)
                    customerUtility.alert(result.DESCRIPTION,'s');
                else
                    customerUtility.alert(result.DESCRIPTION,'e');
            })
        }
        //#endregion 資料上傳(Excel 資料寫入 local sql)

        //#region fileSubmitFunction (把檔案上傳到指定資料夾)
        function fileSubmitFunction() {
            var dataString;
            var action = $("#form0").attr("action");
            if ($("#form0").attr("enctype") == "multipart/form-data") {
                dataString = new FormData($("#form0").get(0));
                processData = false;
            }
            else {
                // regular form, do your own thing if you need it
            }
            clearJqgrid();
            $.ajax({
                type: "POST",
                url: action,
                data: dataString,
                dataType: "json",
                contentType: false,
                processData: false,
                success: function (result) {
                    if (result.RETURN_FLAG) {
                        createJqgrid(
                          "list1",
                          "pager1",
                          '@Ref.Table_Type.D72.tableNameGetDescription()',
                          url.type +"Excel"
                          );
                        $('#btnTransfer').prop('disabled', false);
                    }
                    else {
                        customerUtility.alert(result.DESCRIPTION,'w');
                    }
                }
            });
        }
        //#endregion fileSubmitFunction

        //#region clearJqgrid (清除JqGrid)
        function clearJqgrid() {
            $('#jqgridDiv').children().remove();
        }
        //#endregion clearJqgrid

        //#region createJqgrid (建立JqGrid套件)
        //listId (Jqgrid產生table的ID)
        //pagerId (下方產生筆數的ID)
        //colNameArray (設定上方Title *要與Data 傳入Json 屬性相對應)
        //colModelArray
        //title (標題)
        //type Db(查詢) Excel(上傳儲存)
        function createJqgrid(listId, pagerId, title, type) {
            var colNameArray = @Html.Raw(Json.Encode(ViewBag.jqgridColNames));
            var colModelArray = @Html.Raw(Json.Encode(ViewBag.jqgridColModel));
            $('#jqgridDiv').append('<table id="' + listId + '"></table>');
            $('#jqgridDiv').append('<div id="' + pagerId + '"></div>');
            $("#" + listId).jqGrid({
                url: url.getDbData,
                datatype: "json",
                mtype: "POST",
                postData:
                {
                    type: type,
                },
                jsonReader:
                {
                    repeatitems: false,
                },
                colNames: colNameArray,
                colModel: colModelArray,
                 rowNum: jqgridCustom.rowNum(), //一頁筆數
                rowList: jqgridCustom.rowList(), //設定一頁幾筆
                pager: '#' + pagerId,
                height: jqgridCustom.getHeight(),
                width: jqgridCustom.getwidth(),
                //sortname: 'id',
                sortorder: "desc",
                caption: title, //標題
                resizable: false,
                shrinkToFit: false,
                autoencode: true,
                viewsortcols: [true, 'vertical', true],
                viewrecords: true, //顯示總數
                ajaxRowOptions: { contentType: "application/json" },
                serializeRowData: function (data) {
                    return JSON.stringify(data);
                },
                loadComplete: function () {
                    var table = $(this);
                    jqgridCustom.updatePagerIcons(table);
                }
            });
            $("#" + listId).jqGrid('navGrid', '#' + pagerId, { edit: false, add: false, del: false });           
        }
        //#endregion createJqgrid
    });
</script>