Transfer/ViewModels/A94ViewModel.cs
using System.ComponentModel;

namespace Transfer.ViewModels
{
    /// <summary>
    /// A94 View Data
    /// </summary>
    public class A94ViewModel
    {
        [Description("國家")]
        public string Country { get; set; }

        [Description("政府債務/GDP Ticker")]
        public string IGS_Index_Map { get; set; }

        [Description("短期外債 Ticker")]
        public string Short_term_Debt_Map { get; set; }

        [Description("外匯儲備 Ticker")]
        public string Foreign_Exchange_Map { get; set; }

        [Description("年度GDP Y/Y Ticker")]
        public string GDP_Yearly_Map { get; set; }
    }
}

Transfer/Controllers/A9Controller.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Web.Mvc;
using Transfer.Infrastructure;
using Transfer.Models.Interface;
using Transfer.Models.Repository;
using Transfer.Utility;
using Transfer.ViewModels;
using System.Linq;
using static Transfer.Enum.Ref;

namespace Transfer.Controllers
{
    [LogAuth]
    public class A9Controller : CommonController
    {
        private IA9Repository A9Repository;
        private List<SelectOption> actions = null;
        DateTime startTime = DateTime.MinValue;
        public A9Controller()
        {
            actions = new List<SelectOption>() {
                new SelectOption() {Text="查詢",Value="search" },
                new SelectOption() {Text="上傳&存檔",Value="upload" }};
            this.A9Repository = new A9Repository();
            startTime = DateTime.Now;
        }

        /// <summary>
        /// A94(主權債測試指標_Ticker)
        /// </summary>
        /// <returns></returns>
        [UserAuth]
        public ActionResult A94()
        {
            return View();
        }

        /// <summary>
        /// A95_1(主權債測試指標_Ticker)
        /// </summary>
        /// <returns></returns>
        [UserAuth]
        public ActionResult A95_1Detail()
        {
            ViewBag.action = new SelectList(actions, "Value", "Text");
            var jqgridInfo = FactoryRegistry.GetInstance(Table_Type.A95_1).TojqGridData(new int[] {100,150,230,190,165,100 },null,true);
            ViewBag.jqgridColNames = jqgridInfo.colNames;
            ViewBag.jqgridColModel = jqgridInfo.colModel;
            return View();
        }

        public ActionResult A96Detail()
        {
            ViewBag.action = new SelectList(actions, "Value", "Text");
            var jqgridInfo = FactoryRegistry.GetInstance(Table_Type.A96).TojqGridData();
            ViewBag.jqgridColNames = jqgridInfo.colNames;
            ViewBag.jqgridColModel = jqgridInfo.colModel;
            return View();
        }

        public ActionResult A96DateDetail()
        {
            ViewBag.action = new SelectList(actions, "Value", "Text");
            var jqgridInfo = FactoryRegistry.GetInstance(Table_Type.A96_Trade).TojqGridData(null, null, true);
            ViewBag.jqgridColNames = jqgridInfo.colNames;
            ViewBag.jqgridColModel = jqgridInfo.colModel;
            return View();
        }

        #region GetA94All
        [HttpPost]
        public JsonResult GetA94AllData()
        {
            MSGReturnModel result = new MSGReturnModel();
            result.RETURN_FLAG = false;
            result.DESCRIPTION = Message_Type.not_Find_Any.GetDescription();

            try
            {
                var queryResult = A9Repository.getA94All();

                result.RETURN_FLAG = queryResult.Item1;

                Cache.Invalidate(CacheList.A94DbfileData); //清除
                Cache.Set(CacheList.A94DbfileData, queryResult.Item2); //把資料存到 Cache

                if (!result.RETURN_FLAG)
                {
                    result.DESCRIPTION = Message_Type.not_Find_Any.GetDescription();
                }
            }
            catch (Exception ex)
            {
                result.RETURN_FLAG = false;
                result.DESCRIPTION = ex.Message;
            }

            return Json(result);
        }
        #endregion

        #region GetCacheA94Data
        [HttpPost]
        public JsonResult GetCacheA94Data(jqGridParam jdata)
        {
            List<A94ViewModel> data = new List<A94ViewModel>();
            if (Cache.IsSet(CacheList.A94DbfileData))
            {
                data = (List<A94ViewModel>)Cache.Get(CacheList.A94DbfileData);
            }

            return Json(jdata.modelToJqgridResult(data));
        }
        #endregion

        #region GetA94Data
        [BrowserEvent("查詢A94資料")]
        [HttpPost]
        public JsonResult GetA94Data(A94ViewModel dataModel)
        {
            MSGReturnModel result = new MSGReturnModel();
            result.RETURN_FLAG = false;
            result.DESCRIPTION = Message_Type.not_Find_Any.GetDescription();

            try
            {
                var queryResult = A9Repository.getA94(dataModel);

                result.RETURN_FLAG = queryResult.Item1;

                Cache.Invalidate(CacheList.A94DbfileData); //清除
                Cache.Set(CacheList.A94DbfileData, queryResult.Item2); //把資料存到 Cache

                if (!result.RETURN_FLAG)
                {
                    result.DESCRIPTION = Message_Type.not_Find_Any.GetDescription();
                }
            }
            catch (Exception ex)
            {
                result.RETURN_FLAG = false;
                result.DESCRIPTION = ex.Message;
            }

            return Json(result);
        }
        #endregion

        #region SaveA94
        [BrowserEvent("儲存A94資料")]
        [HttpPost]
        public JsonResult SaveA94(string actionType, A94ViewModel dataModel)
        {
            MSGReturnModel result = new MSGReturnModel();

            result.RETURN_FLAG = false;
            result.DESCRIPTION = Message_Type.parameter_Error.GetDescription();

            try
            {
                MSGReturnModel resultSave = A9Repository.saveA94(actionType, dataModel);

                result.RETURN_FLAG = resultSave.RETURN_FLAG;
                result.DESCRIPTION = Message_Type.save_Success.GetDescription();

                if (!result.RETURN_FLAG)
                {
                    result.DESCRIPTION = Message_Type.save_Fail.GetDescription() + " " + resultSave.DESCRIPTION;
                }
            }
            catch (Exception ex)
            {
                result.RETURN_FLAG = false;
                result.DESCRIPTION = ex.Message;
            }

            return Json(result);
        }
        #endregion

        #region DeleteA94
        [BrowserEvent("A94刪除資料")]
        [HttpPost]
        public JsonResult DeleteA94(string country)
        {
            MSGReturnModel result = new MSGReturnModel();

            result.RETURN_FLAG = false;
            result.DESCRIPTION = Message_Type.parameter_Error.GetDescription();

            try
            {
                MSGReturnModel resultDelete = A9Repository.deleteA94(country);

                result.RETURN_FLAG = resultDelete.RETURN_FLAG;
                result.DESCRIPTION = Message_Type.delete_Success.GetDescription();

                if (!result.RETURN_FLAG)
                {
                    result.DESCRIPTION = Message_Type.delete_Fail.GetDescription(resultDelete.DESCRIPTION);
                }
            }
            catch (Exception ex)
            {
                result.RETURN_FLAG = false;
                result.DESCRIPTION = ex.Message;
            }

            return Json(result);
        }
        #endregion

        #region A95_1

        /// <summary>
        /// 查詢 A95_1(產業別對應Ticker補登檔) 資料
        /// </summary>
        /// <returns></returns>
        [BrowserEvent("查詢 A95_1(產業別對應Ticker補登檔) 資料")]
        [HttpPost]
        public JsonResult GetA95_1Data(string bondNumber)
        {
            MSGReturnModel result = new MSGReturnModel();
            var datas = A9Repository.getA95_1(bondNumber);
            if (datas.Any())
            {
                Cache.Invalidate(CacheList.A95_1DbfileData); //清除
                Cache.Set(CacheList.A95_1DbfileData, datas); //把資料存到 Cache
                result.RETURN_FLAG = true;                
            }
            else
            {
                result.RETURN_FLAG = false;
                result.DESCRIPTION = Message_Type.not_Find_Any.GetDescription(Table_Type.A95_1.tableNameGetDescription());
            }
            return Json(result);
        }

        /// <summary>
        /// 轉檔把Excel 資料存到 DB
        /// </summary>
        /// <returns></returns>
        [BrowserEvent("A95_1(產業別對應Ticker補登檔)Excel檔存到DB")]
        [HttpPost]
        public JsonResult TransferA95_1()
        {
            MSGReturnModel resultA95_1 = new MSGReturnModel();
            try
            {
                #region 抓Excel檔案 轉成 model

                // Excel 檔案位置

                string projectFile = Server.MapPath("~/" + SetFile.FileUploads);

                string fileName = string.Empty;
                if (Cache.IsSet(CacheList.A95_1ExcelName))
                    fileName = (string)Cache.Get(CacheList.A95_1ExcelName);  //從Cache 抓資料

                if (fileName.IsNullOrWhiteSpace())
                {
                    resultA95_1.RETURN_FLAG = false;
                    resultA95_1.DESCRIPTION = Message_Type.time_Out.GetDescription();
                    return Json(resultA95_1);
                }

                string path = Path.Combine(projectFile, fileName);

                List<A95_1ViewModel> dataModel = new List<A95_1ViewModel>();

                string errorMessage = string.Empty;

                using (FileStream stream = System.IO.File.Open(path, FileMode.Open, FileAccess.Read))
                {
                    //Excel轉成 Exhibit10Model
                    string pathType = path.Split('.')[1]; //抓副檔名
                    var data = A9Repository.getA95_1Excel(pathType, stream);
                    dataModel = data.Item2;
                    errorMessage = data.Item1;
                }
                if (!errorMessage.IsNullOrWhiteSpace())
                {
                    resultA95_1.RETURN_FLAG = false;
                    resultA95_1.DESCRIPTION = errorMessage;
                    return Json(resultA95_1);
                }
                #endregion 抓Excel檔案 轉成 model

                #region txtlog 檔案名稱

                string txtpath = SetFile.A95_1TransferTxtLog; //預設txt名稱

                #endregion txtlog 檔案名稱

                #region save Assessment_Sub_Kind_Ticker(A95_1)

                resultA95_1 = A9Repository.insertA95_1(dataModel); //save to DB
                CommonFunction.saveLog(Table_Type.A95_1,

Transfer/Views/A9/A96Detail.cshtml
@using Transfer.Utility;
@using Transfer.Enum;
@{
    ViewBag.Menu = "A9Main";
    ViewBag.SubMenu = "A96Sub";
    ViewBag.Title = "A96(信用利差資料)";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container" id="main">
    <div class="row main_hand">
        <div class="col-md-12 main_hand_div">
            <form id="myForm">
                <table>
                    <tr>
                        <td style="">
                            <label>選擇動作 : </label>
                            @Html.DropDownList("action",
                           (SelectList)ViewBag.action,
                            new { @class = "form-control", @style = "display:inline-block" })
                        </td>
                    </tr>
                    <tr class="action search">
                        <td style="">
                            <table>
                                <tr>
                                    <td style="width:580px" class="form-group">
                                        <label>報導日 : </label>&emsp;
                                        <input type="text" id="datepicker1" name="datepicker1">
                                    </td>
                                    <td style="width:450px; padding-top:8px">
                                        <table>
                                            <tr>
                                                <td>
                                                    <label>版本 : &nbsp;&nbsp;</label>
                                                </td>
                                                <td>
                                                    <div class="select-editable">
                                                        <select id="versionSelect" onchange="this.nextElementSibling.value=this.value"></select>
                                                        <input type="text" name="version" id="version" value="" />
                                                    </div>
                                                </td>
                                                <td></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" style="padding-top:10px">
                                        <input type="button" class="btn btn-primary" value="查詢" id="btnA96Search" style="margin-left:30px;" />
                                        <input type="button" class="btn btn-primary dlexcel" style="margin-left:10px;" value="下載A96Excel" id="btnA96Dl" disabled />
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </form>
            <table>
                <tr class="action upload" style="display:none">
                    <td style="padding-top:10px;">
                        @using (Ajax.BeginForm("UploadA96", "A9",
                         new AjaxOptions { HttpMethod = "POST" },
                         new { enctype = "multipart/form-data", @id = "form0" }))
                        {
                            <input type="file" name="file" class="filestyle" data-buttonName="btn-primary" data-buttonText="轉檔檔案" style="margin-right:10px" />
                        }
                    </td>
                    <td style="padding-top:10px;">
                        <input type="button" class="btn btn-primary" style="margin-right:10px" value="資料上傳" id="fileSubmit" />
                        <input type="button" class="btn btn-primary" value="轉檔" id="btnTransfer" disabled />
                    </td>
                </tr>
            </table>
        <i class="fa fa-exclamation-circle title" style="font-size:24px;"
           alt="說明：

"></i>
        </div>
    </div>
    <div class="row main_body" style="overflow:auto;height:100%">
        <div class="col-md-12">
            <div class="viewDetail">
                <div id="jqgridDiv" class="jqd">
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        //#region 註冊URL
        var url = {};
        url.getReportDataVersion = '@Url.Action("GetA96Version", "A9")';
        url.type = '@Ref.Table_Type.A96.ToString()';
        url.search = '@Url.Action("GetA96", "A9")';
        url.getDbData = '@Url.Action("GetCacheData", "A9")';
        url.transfer = '@Url.Action("TransferA96", "A9")';
        url.getA96Excel = '@Url.Action("GetA96Excel","A9")';
        //#endregion 註冊URL

        //#region 選擇reportDate 後要觸發的動作
        var versionFun = customerUtility.getVersion('versionSelect',
            'datepicker1',
            '@Ref.Table_Type.A96.ToString()',
            url.getReportDataVersion);
        //#endregion 選擇reportDate 後要觸發的動作

        //#region 產生datepicker
        created.createDatepicker('datepicker1', true, '', versionFun);
        //#endregion

        //#region 註冊verified
        verified.datepicker("myForm", "datepicker1", false, $('#datepicker1').val());
        verified.required('myForm', 'version', message.required(message.version));
        verified.number('myForm', 'version');
        //#endregion 註冊verified

        $('#action').on('change', function () {
            clearJqgrid();
            $('#btnTransfer').prop('disabled', true);
            $('.action').hide();
            var opencls = $(this).val();
            $('.' + opencls).show();
        });

        //#region 註冊click事件
        $('input:button').each(function () {
            var id = $(this).attr('id');
            switch (id) {
                case 'btnA96Search':
                    $('#' + id).on('click', function () { A96Search() });
                    break;
                case 'btnA96Dl':
                    $('#' + id).click(A96DlExcel);
                    break;
                case 'fileSubmit':
                    $('#' + id).click(fileSubmitFunction);
                    break;
                case 'btnTransfer':
                    $('#' + id).click(transfer);
                    break;
            }
        })
        //#endregion 註冊click事件

        function A96DlExcel() {
            $.ajax({
                type: "POST",
                url: url.getA96Excel,
                contentType: 'application/json',
            })
            .done(function (result) {
                if (result.RETURN_FLAG)
                    window.location.href = "@Url.RouteUrl(new
                { Controller = "A9", Action = "DownloadExcel"})/?type=" + '@Ref.Excel_DownloadName.A96.ToString()';
                else
                customerUtility.alert(result.DESCRIPTION,'e');
            })
        }

        function A96Search() {
            if ($('#myForm').valid()) {
                clearJqgrid();
                $.ajax({
                    type: "POST",
                    data: JSON.stringify({
                        reportDate : $('#datepicker1').val(),
                        version : $('#version').val(),
                    }),
                    dataType: "json",
                    url: url.search,
                    contentType: 'application/json',
                })
                .done(function (result) {
                    $('#btnA96Dl').prop('disabled',!result.RETURN_FLAG);
                    if (result.RETURN_FLAG) {                      
                        createJqgrid(
                            "list1",
                            "pager1",
                            url.type +"DB"
                            );
                    }
                    else
                        customerUtility.alert(result.DESCRIPTION,'e');
                })
            }
        }

        //#region 資料上傳(Excel 資料寫入 local sql)
        function transfer() {
            $.ajax({
                type: "POST",
                url: url.transfer,
                contentType: 'application/json'
            })
            .done(function (result) {
                if (result.RETURN_FLAG)
                    customerUtility.alert(result.DESCRIPTION,'s');
                else
                    customerUtility.alert(result.DESCRIPTION,'e');
            })
        }
        //#endregion 資料上傳(Excel 資料寫入 local sql)

        //#region fileSubmitFunction (把檔案上傳到指定資料夾)
        function fileSubmitFunction() {
            var dataString;
            var action = $("#form0").attr("action");
            if ($("#form0").attr("enctype") == "multipart/form-data") {
                dataString = new FormData($("#form0").get(0));
                processData = false;
            }
            else {
                // regular form, do your own thing if you need it
            }
            clearJqgrid();
            $.ajax({
                type: "POST",
                url: action,
                data: dataString,
                dataType: "json",
                contentType: false,
                processData: false,
                success: function (result) {
                    if (result.RETURN_FLAG) {
                        createJqgrid(
                          "list1",
                          "pager1",
                          url.type +"Excel"
                          );
                        $('#btnTransfer').prop('disabled', false);
                    }
                    else {
                        customerUtility.alert(result.DESCRIPTION,'w');
                    }
                }
            });
        }
        //#endregion fileSubmitFunction

        //#region clearJqgrid (清除JqGrid)
        function clearJqgrid() {
            $('#jqgridDiv').children().remove();
        }
        //#endregion clearJqgrid

        //#region createJqgrid (建立JqGrid套件)
        //listId (Jqgrid產生table的ID)
        //pagerId (下方產生筆數的ID)
        //colNameArray (設定上方Title *要與Data 傳入Json 屬性相對應)
        //colModelArray
        function createJqgrid(listId, pagerId,type) {
            var colNameArray = @Html.Raw(Json.Encode(ViewBag.jqgridColNames));
            var colModelArray = @Html.Raw(Json.Encode(ViewBag.jqgridColModel));
            $('#jqgridDiv').append('<table id="' + listId + '"></table>');
            $('#jqgridDiv').append('<div id="' + pagerId + '"></div>');
            $("#" + listId).jqGrid({
                url: url.getDbData,
                datatype: "json",
                mtype: "POST",
                postData:
                {
                    type: type,
                },
                jsonReader:
                {
                    repeatitems: false,
                },
                colNames: colNameArray,
                colModel: colModelArray,
                rowNum: jqgridCustom.rowNum(), //一頁筆數
                rowList: jqgridCustom.rowList(), //設定一頁幾筆
                pager: '#' + pagerId,
                height: jqgridCustom.getHeight(),
                width: jqgridCustom.getwidth(),
                //sortname: 'id',
                sortorder: "desc",
                caption:  '@Ref.Table_Type.A96.tableNameGetDescription()', //標題
                resizable: false,
                shrinkToFit: false,
                autoencode: true,
                viewsortcols: [true, 'vertical', true],
                viewrecords: true, //顯示總數
                ajaxRowOptions: { contentType: "application/json" },
                serializeRowData: function (data) {
                    return JSON.stringify(data);
                },
                loadComplete: function () {
                    var table = $(this);
                    jqgridCustom.updatePagerIcons(table);
                }
            });
            $("#" + listId).jqGrid('navGrid', '#' + pagerId, { edit: false, add: false, del: false });
        }
        //#endregion createJqgrid
    });
</script>